//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XVLauncher.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang_your_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_your_lang() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XVLauncher.Properties.Langs.Lang.your_lang", typeof(Lang_your_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Deleting files....
        /// </summary>
        public static string deleting {
            get {
                return ResourceManager.GetString("deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download completed..
        /// </summary>
        public static string download_completed {
            get {
                return ResourceManager.GetString("download_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It is not possible to install the game. Check your internet connection or retry in a few minutes.
        /// </summary>
        public static string download_not_possible {
            get {
                return ResourceManager.GetString("download_not_possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download in progress... Downloaded: {0:0.##} {1}
        ///Note: the download size is approximately {2}..
        /// </summary>
        public static string download_progress_unknown {
            get {
                return ResourceManager.GetString("download_progress_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The file {0} was not found..
        /// </summary>
        public static string exe_not_found {
            get {
                return ResourceManager.GetString("exe_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorry, the process to intall fonts must be run as Administrator..
        /// </summary>
        public static string fonts_exception {
            get {
                return ResourceManager.GetString("fonts_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All fonts are now installed. The game will need to be run as an administrator to apply the changes..
        /// </summary>
        public static string fonts_installed {
            get {
                return ResourceManager.GetString("fonts_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installing fonts.
        /// </summary>
        public static string fonts_installing {
            get {
                return ResourceManager.GetString("fonts_installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All necessary fonts will be reinstalled the next time the game is started..
        /// </summary>
        public static string fonts_next_launch {
            get {
                return ResourceManager.GetString("fonts_next_launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Some fonts required for the game are not present in your system.
        ///They will be intalled now, but you must consent to run the application as an administrator..
        /// </summary>
        public static string fonts_will_be_installed {
            get {
                return ResourceManager.GetString("fonts_will_be_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Game version {0}.
        /// </summary>
        public static string game_version {
            get {
                return ResourceManager.GetString("game_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There was an error decompressing the game. Please, try to uninstall it from setting menu and then download it again.
        ///Error details: {0}.
        /// </summary>
        public static string installation_error {
            get {
                return ResourceManager.GetString("installation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installation in progress... {0:0.##}%.
        /// </summary>
        public static string installation_ip {
            get {
                return ResourceManager.GetString("installation_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This is the last version available..
        /// </summary>
        public static string last_version_av {
            get {
                return ResourceManager.GetString("last_version_av", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Launcher version {0}.
        /// </summary>
        public static string launcher_version {
            get {
                return ResourceManager.GetString("launcher_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Powered by open-source software.
        /// </summary>
        public static string opensource {
            get {
                return ResourceManager.GetString("opensource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Other options.
        /// </summary>
        public static string other_options {
            get {
                return ResourceManager.GetString("other_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The game is installed in a path too long, this may cause problems playing with the &quot;New Engine&quot; option enabled. Please, move the launcher folder to a shorter path or uncheck the &quot;New Engine&quot; option from the settings..
        /// </summary>
        public static string path_too_long {
            get {
                return ResourceManager.GetString("path_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recover.
        /// </summary>
        public static string recover {
            get {
                return ResourceManager.GetString("recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Game recovery.
        /// </summary>
        public static string recovery {
            get {
                return ResourceManager.GetString("recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All game files will be deleted and the last version available will be downloaded.
        ///You will not loose your save data.
        ///Do you want to continue?.
        /// </summary>
        public static string recovery_text {
            get {
                return ResourceManager.GetString("recovery_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reinstall fonts.
        /// </summary>
        public static string reinstall_fonts {
            get {
                return ResourceManager.GetString("reinstall_fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select save.
        /// </summary>
        public static string save_picker {
            get {
                return ResourceManager.GetString("save_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save 1.
        /// </summary>
        public static string save1 {
            get {
                return ResourceManager.GetString("save1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save 2.
        /// </summary>
        public static string save2 {
            get {
                return ResourceManager.GetString("save2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save 3.
        /// </summary>
        public static string save3 {
            get {
                return ResourceManager.GetString("save3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save 4.
        /// </summary>
        public static string save4 {
            get {
                return ResourceManager.GetString("save4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save 5.
        /// </summary>
        public static string save5 {
            get {
                return ResourceManager.GetString("save5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save 6.
        /// </summary>
        public static string save6 {
            get {
                return ResourceManager.GetString("save6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt; Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download in progress... {0:0.##}%.
        /// </summary>
        public static string sownload_progress {
            get {
                return ResourceManager.GetString("sownload_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Third-party software used in XVLauncher.
        /// </summary>
        public static string third_party {
            get {
                return ResourceManager.GetString("third_party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to download the game: {0}.
        /// </summary>
        public static string unable_download {
            get {
                return ResourceManager.GetString("unable_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Uninstall.
        /// </summary>
        public static string uninstall {
            get {
                return ResourceManager.GetString("uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It is not possible to check for updates now. Check your internet connection or try again in a few minutes. You can still play the game..
        /// </summary>
        public static string update_not_possible {
            get {
                return ResourceManager.GetString("update_not_possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use new engine.
        /// </summary>
        public static string use_engine {
            get {
                return ResourceManager.GetString("use_engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It is recommended to keep this setting active. However, it can be disabled if your computer is not compatible with the new engine..
        /// </summary>
        public static string use_engine_tooltip {
            get {
                return ResourceManager.GetString("use_engine_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Version {0}. .
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Version {0} available for the download..
        /// </summary>
        public static string version_available {
            get {
                return ResourceManager.GetString("version_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning!.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Based on XVLauncher, the open-source launcher for your app.
        /// </summary>
        public static string xvlauncher {
            get {
                return ResourceManager.GetString("xvlauncher", resourceCulture);
            }
        }
    }
}
